matrix:
  include:
    - language: go
      sudo: false
      go:
        - "1.11.x"
      env:
        - GO111MODULE=on
      install: true

      script:
        - go test ./... -race -coverprofile=coverage.txt -covermode=atomic -v

      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd website
      before_script:
        - yarn start &
        - while true; do if nc -zvw 1 localhost 3000; then break; else sleep 1; fi done;
      env:
        - REACT_APP_BACKEND_URL='https://api.yopass.se'
