language: go
sudo: false
go:
  - "1.11.x"
  - tip

env:
  - GO111MODULE=on
install: true

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
