matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd website
      before_script:
        # Reduce cold start errors in tests.
        - curl --fail -s https://api.yopass.se/secret/c76cb66a-a125-47a6-a98a-492eec1d64ed || true
        - yarn start &
        - while [[ ! $(curl -s --max-time 1 http://localhost:3000 |grep -i yopass) ]]; do echo 'waiting for startup' && sleep 1; done
      env:
        - REACT_APP_BACKEND_URL='https://api.yopass.se'
      script:
        - travis_retry yarn run test
