[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/gomemcache"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"
